@startgantt

printscale daily zoom 2
today is colored in Red

legend
|= Color |= 状態 |
|<#LightGreen>| 完了 |
|<#LightBlue>| 進行中 |
|<#LightGray>| 未着手 |
end legend

title Progress Gantt
Project starts 2026-01-01
saturday are closed
sunday are closed

-- main --
-- 要件定義 --
[A_ID_1] starts 2026-01-01
[A_ID_1] requires 30 days
[A_ID_1] is 0% completed
[A_ID_1] is colored in LightBlue
[A_ID_1] starts after [A_ID_1]'s end

-- 設計 --
[A_ID_2] starts 2026-01-01
[A_ID_2] requires 30 days
[A_ID_2] is 1% completed
[A_ID_2] is colored in LightGreen
[A_ID_2] starts after [A_ID_1]'s end

-- sub --
-- 実装 --
[B_ID_3] starts 2026-01-01
[B_ID_3] requires 30 days
[B_ID_3] is 0% completed
[B_ID_3] is colored in LightBlue
[B_ID_3] starts after [A_ID_2]'s end

@endgantt